# Streamlit Cloud Secrets Configuration
# Copy this content to: App Settings → Secrets in Streamlit Cloud dashboard

# ============================================================================
# AUTHENTICATION (REQUIRED - Change this password!)
# ============================================================================
# PUBLIC_PASSWORD - NO LONGER NEEDED (public booking is now open to everyone)
STAFF_PASSWORD = "staff2024"  # Change this!

# ============================================================================
# TURSO DATABASE (REQUIRED for Production)
# ============================================================================
USE_TURSO = "true"
TURSO_DATABASE_URL = "libsql://wellspring-tmeasley.aws-us-east-1.turso.io"
TURSO_AUTH_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3NjE2NjI5MjYsImlkIjoiNjVjNDgwM2ItY2VlYS00N2IwLTk1YWUtOWE5MGYyYzY0YjYzIiwicmlkIjoiYTlmNWFlYTgtZWQzOC00YmYyLThlOTktODNmNjk5YWY3MjIyIn0.TaSXzPClMfrgphBw29scFP_vy0_XgQgyukM45xwdaDoZ6SOqjDpmNyp0HKzqn6FN1-NcYH66uDB6rOjvw0S0Cg"

# ============================================================================
# EMAIL NOTIFICATIONS (Optional - Configure ProtonMail)
# ============================================================================
# SMTP_SERVER = "smtp.protonmail.com"
# SMTP_PORT = "587"
# SMTP_USERNAME = "SpringMountainWellness@proton.me"
# SMTP_PASSWORD = "your_protonmail_app_password_here"
# FROM_EMAIL = "SpringMountainWellness@proton.me"

# ============================================================================
# IMPORTANT NOTES:
# ============================================================================
# 1. Change STAFF_PASSWORD immediately after first deployment!
# 2. Public booking is now OPEN - no password required for guests
# 3. These secrets are encrypted by Streamlit Cloud
# 4. Never commit this file to GitHub with real passwords
# 5. App will auto-restart when you save secrets changes
# 6. Turso credentials are already filled in from your setup
